export enum ErrorCode {
  // биллинг / токены
  TOKENS_NOT_ENOUGH = "TOKENS_NOT_ENOUGH",

  // модель / джобы
  MODEJ_JOB_TYPE_NOT_FOUND = "MODEJ_JOB_TYPE_NOT_FOUND",
  MODEL_JOB_NOT_FOUND = "MODEL_JOB_NOT_FOUND",
  MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE",

  // нейросети
  MODERATION_BLOCKED = "MODERATION_BLOCKED",

  // доступ
  UNAUTHORIZED = "UNAUTHORIZED",
  EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
  ACCOUNT_IS_BLOCKED = "ACCOUNT_IS_BLOCKED",
  FORBIDDEN = "FORBIDDEN",

  // валидация
  VALIDATION_FAILED = "VALIDATION_FAILED",

  // дефолт для необработанных
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
