FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

# dev окружение
ENV NODE_ENV=development
ENV LOG_LEVEL=debug

# монтируем код из хоста
VOLUME ["/app"]

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
